# Configuration Sync Script
# Para Shooting Committee of India

Write-Host "Syncing Frontend and Backend Configuration..." -ForegroundColor Cyan
Write-Host ""

# Read backend PORT
$backendEnvPath = "apps\api\.env"
$frontendEnvPath = "apps\web\.env.local"

if (-not (Test-Path $backendEnvPath)) {
    Write-Host "Backend .env file not found!" -ForegroundColor Red
    exit 1
}

$backendContent = Get-Content $backendEnvPath
$portLine = $backendContent | Where-Object { $_ -match "^PORT=" }
$backendPort = if ($portLine) { $portLine.Split('=')[1].Trim() } else { "4000" }

$apiPrefixLine = $backendContent | Where-Object { $_ -match "^API_PREFIX=" }
$apiPrefix = if ($apiPrefixLine) { $apiPrefixLine.Split('=')[1].Trim() } else { "api/v1" }

Write-Host "Backend Configuration:" -ForegroundColor Green
Write-Host "  PORT: $backendPort"
Write-Host "  API_PREFIX: $apiPrefix"
Write-Host ""

# Create frontend .env.local

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Read JWT_SECRET from backend
$jwtSecretLine = $backendContent | Where-Object { $_ -match "^JWT_SECRET=" }
$jwtSecret = if ($jwtSecretLine) { $jwtSecretLine.Split('=')[1].Trim() } else { "default-secret-change-in-production" }

$frontendConfig = @"
# FRONTEND ENVIRONMENT VARIABLES
# Auto-generated by sync-config.ps1
# Last updated: $timestamp

# API Configuration
# NEXT_PUBLIC_API_URL is relative for the client-side proxy (browser)
NEXT_PUBLIC_API_URL=$apiPrefix
# API_URL is absolute for Server Components (Node.js) - Direct to Backend
API_URL=http://localhost:$backendPort/$apiPrefix

# Environment
NODE_ENV=development
NEXT_PUBLIC_ENV=development

# Feature Flags
NEXT_PUBLIC_DEBUG_MODE=true
NEXT_PUBLIC_ENABLE_ANALYTICS=false
NEXT_PUBLIC_ENABLE_SENTRY=false

# Application Metadata
NEXT_PUBLIC_APP_NAME=Para Shooting Committee of India
NEXT_PUBLIC_APP_VERSION=1.0.0

# JWT Secret (synced from backend)
# CRITICAL: This allows the middleware to verify backend-issued tokens
JWT_SECRET=$jwtSecret
"@

Set-Content -Path $frontendEnvPath -Value $frontendConfig

Write-Host "Frontend .env.local updated" -ForegroundColor Green
Write-Host "  NEXT_PUBLIC_API_URL: $apiPrefix (Relative for proxy)" -ForegroundColor Green
Write-Host "  JWT_SECRET: Synced from backend" -ForegroundColor Green
Write-Host ""

Write-Host "Configuration is in sync!" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  Backend API: http://localhost:$backendPort/$apiPrefix" -ForegroundColor White
Write-Host "  Frontend: http://localhost:3000" -ForegroundColor White
Write-Host "  Database: localhost:5432" -ForegroundColor White
Write-Host ""
Write-Host "Configuration sync complete!" -ForegroundColor Cyan
